---
  extends: airbnb-base
  env:
    node: true
    mocha: true
    es6: true
  parser: '@typescript-eslint/parser'
  parserOptions:
    sourceType: module
    ecmaFeatures:
      modules: true
  settings:
    import/resolver:
      node:
        extensions:
          - .js
          - .ts
  rules:
    import/extensions: 0
    import/no-extraneous-dependencies:
      - 2
      - devDependencies: true
